# lightning.pytorch==2.6.1
seed_everything: 666
trainer:
  logger:
    class_path: lightning.pytorch.loggers.MLFlowLogger
    init_args:
      experiment_name: xp1_models_or_stats
      run_name: baseline_mean
      log_model: True
      artifact_location: /scratch/shared/cams-dl-ensemble/mlartifacts
  max_steps: 1

model:
  learning_rate: 0.0001
  model:
    class_path: mfai.pytorch.models.IdentityModel
  loss:
    class_path: torch.nn.MSELoss

data:
  models:
    - match
    - minni
    - chimere
    - mocage
    - monarch
    - euradim
    - emep
    - gemaq
    - silam
    - dehm
    - lotos
  lead_times:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
    - 11
    - 12
    - 13
    - 14
    - 15
    - 16
    - 17
    - 18
    - 19
    - 20
    - 21
    - 22
    - 23
    - 24
    - 25
    - 26
    - 27
    - 28
    - 29
    - 30
    - 31
    - 32
    - 33
    - 34
    - 35
    - 36
    - 37
    - 38
    - 39
    - 40
    - 41
    - 42
    - 43
    - 44
    - 45
    - 46
    - 47
    - 48
    - 49
    - 50
    - 51
    - 52
    - 53
    - 54
    - 55
    - 56
    - 57
    - 58
    - 59
    - 60
    - 61
    - 62
    - 63
    - 64
    - 65
    - 66
    - 67
    - 68
    - 69
    - 70
    - 71
    - 72
    - 73
    - 74
    - 75
    - 76
    - 77
    - 78
    - 79
    - 80
    - 81
    - 82
    - 83
    - 84
    - 85
    - 86
    - 87
    - 88
    - 89
    - 90
    - 91
    - 92
    - 93
    - 94
    - 95
    - 96
  species:
    - O3
    - CO
    - NO2
    - SO2
    - PM2P5
    - PM10
  levels:
    - 0
  batch_size: 2
  num_workers: 3
  prefetch_factor: 2
  transforms:
    - class_path: cams.transforms.ExtractInputStatisticalFeatures
      init_args:
        statistic_types:
          - mean