# lightning.pytorch==2.6.1
seed_everything: 666
trainer:
  logger:
    class_path: lightning.pytorch.loggers.MLFlowLogger
    init_args:
      experiment_name: ozone
      run_name: median
      log_model: True
      artifact_location: /scratch/shared/cams-dl-ensemble/mlartifacts
  max_steps: 1
  callbacks:
    - class_path: mfai.pytorch.callbacks.MLFlowSystemMonitorCallback
  max_epochs: 500
  log_every_n_steps: 10

model:
  learning_rate: 0.0001
  model:
    class_path: mfai.pytorch.models.IdentityModel
  loss:
    class_path: torch.nn.MSELoss

data:
  batch_size: 2
  num_workers: 3
  prefetch_factor: 2
  transforms:
    - class_path: cams.transforms.ExtractInputStatisticalFeatures
      init_args:
        statistic_types:
          - median