# lightning.pytorch==2.6.1
seed_everything: 666

trainer:
  logger:
    class_path: lightning.pytorch.loggers.MLFlowLogger
    init_args:
      experiment_name: dummy
      run_name: lea
      log_model: True
      artifact_location: /scratch/shared/cams/mlartifacts

  callbacks:
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        filename: "{epoch:02d}-{val_loss:.2f}"
        monitor: val_loss
        mode: min
        save_top_k: 1    # Save the best model
    - class_path: lightning.pytorch.callbacks.LearningRateMonitor
      init_args:
        logging_interval: step
    - class_path: mfai.pytorch.callbacks.MLFlowSystemMonitorCallback
  max_epochs: 3
  limit_train_batches: 3
  limit_val_batches: 3
  log_every_n_steps: 1

model:
  learning_rate: 0.0001
  model:
    class_path: mfai.pytorch.models.half_unet.HalfUNet
    init_args:
      in_channels: 8  # 2 CAMS models x 2 species x 2 leadtimes
      out_channels: 4  # 2 species x 2 leadtimes
      input_shape:
        - 420
        - 700
      settings:
        num_filters: 8
        autopad_enabled: True
        last_activation: ReLU
  loss:
    class_path: torch.nn.MSELoss

data:
  models:
    - chimere
    - mocage
  species:
    - O3
    - NO2
  lead_times:
    - 15
    - 24
  batch_size: 2
  num_workers: 1
  prefetch_factor: 2
  processed_dir: /scratch/shared/cams-dl-ensemble/all_from_ads/
  # transforms:
  #   - class_path: cams.transforms.ExtractInputStatisticalFeatures
  #     init_args:
  #       statistic_types:
  #         - median
  #         - amax