name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  lint:
    env:
      PYTHONPATH: '.'
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - name: Gather Python changed files
      id: changed-py-files
      uses: tj-actions/changed-files@ed68ef82c095e0d48ec87eccea555d944a631a4c # v46
      with:
        files: |
          cams/**/*.py
          script/**/*.py

    - name: Lint with ruff
      if: steps.changed-py-files.outputs.any_changed == 'true'
      run: |
        pip install ruff==0.15.9
        ruff format --check ${{ steps.changed-py-files.outputs.all_changed_files }}
        ruff check ${{ steps.changed-py-files.outputs.all_changed_files }}

  tests:
    env:
      PYTHONPATH: '.'
      SCIPY_ARRAY_API: 1
    runs-on: ubuntu-22.04
    container:
      image: pytorch/pytorch:2.10.0-cuda12.6-cudnn9-devel

    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v7
      with:
        enable-cache: true

    - name: Set up Python
      run: uv python install

    - name: Install the project
      run: uv sync --locked --all-extras --dev

    - name: Install git  # necessary for the tj-action/changed-py-files
      run: apt-get update && apt-get install -y git

    - name: Gather Python changed files
      id: changed-py-files
      uses: tj-actions/changed-files@ed68ef82c095e0d48ec87eccea555d944a631a4c # v46
      with:
        files: |
          *.py
          **/*.py

    - name: Type hinting with pyright on changed files
      if: steps.changed-py-files.outputs.any_changed == 'true'
      run: |
        uv run pyright ${{ steps.changed-py-files.outputs.all_changed_files }}

    - name: Test with pytest
      if: steps.changed-py-files.outputs.any_changed == 'true'
      run: |
        uv run pytest --cov=cams --cov=scripts --cov-fail-under=95 tests/
